- name: stow folders
  stow:
    name: "{{ item.vars.stow_folder_name }}"
    state: present
    source_dir: "{{ item.vars.stow_folder_parent }}"
    target_dir: "{{ item.vars.stow_target_dir | default(freckles_stow_target_dir) }}"
  ignore_errors: "{{ ignore_errors | default(true) }}"
  when: 'item.vars.stow_source is defined and item.vars.no_stow|default(false)|bool == false'
  with_items:
    - "{{ freckle_vars.get('packages', []) }}"
