- name: check required executables
  required_executable_facts:
    executables_to_check:
      - stow

- name: install epel-release
  install:
    packages:
      - epel-release:
          pkgs:
            other: ignore
  when: '"stow" in executables_missing'

- name: install stow
  install:
    packages:
      - stow
    pkg_mgr: "{{ pkg_mgr | default(omit) }}"
  when: '"stow" in executables_missing'

- debug: var=freckle_vars

- name: stow folders
  stow:
    name: "{{ item.vars.stow_folder_name }}"
    state: present
    source_dir: "{{ item.vars.stow_folder_parent }}"
    target_dir: "{{ item.vars.stow_target_dir | default(freckles_stow_target_dir) }}"
  ignore_errors: "{{ ignore_errors | default(true) }}"
  when: 'item.vars.stow_source is defined and item.vars.no_stow|default(false)|bool == false'
  with_items:
    - "{{ freckle_vars.get('packages', []) }}"
