---
# tasks file for dotfiles
- name: initialize box with basic requirements
  include_role:
    name: makkus.box-basics

- name: checkout freckle(s)
  git:
    dest: "{{ item.dest }}"
    repo: "{{ item.repo }}"
  when: "item.repo is defined and item.repo"
  with_items:
    - "{{ freckles | git_repo_filter }}"

- name: finding freckles folders
  freckles_facts:
    freckles_repos: "{{ freckles }}"

# can only do that on the controller, because dependency requirements
- name: processing freckles folders
  set_fact:
    freckles_metadata: "{{ freckles_folders_raw | read_profile_vars_filter }}"

- name: calculating package list
  set_fact:
    package_install_list: "{{ freckles_metadata | create_package_list_filter }}"

- name: install base packages
  include_role:
    name: makkus.install-packages
  vars:
    profile_name: freckle

- name: "starting profile execution"
  include: "{{ profile_loop_item.key }}.yml"
  vars:
    freckle_profile_folders: "{{ profile_loop_item.value }}"
  static: no
  when: "profile_loop_item is defined and profile_loop_item.key is defined and profile_loop_item.key != '__freckles_default__'"
  with_dict: "{{ freckles_metadata | flatten_profiles_filter }}"
  loop_control:
    loop_var: profile_loop_item


