---
# tasks file for dotfiles
- name: initialize box with basic requirements
  include_role:
    name: makkus.box-basics

- name: checkout freckle(s)
  git:
    dest: "{{ item.dest }}"
    repo: "{{ item.repo }}"
  when: "item.repo is defined and item.repo"
  with_items:
    - "{{ freckles | git_repo_filter }}"

- name: finding freckles folders
  freckles_facts:
    freckles_repos: "{{ freckles }}"

# can only do that on the controller, because dependency requirements
- name: processing freckles folders
  set_fact:
    freckles_metadata: "{{ freckles_folders_raw | read_profile_vars_filter }}"

- name: calculating package list
  set_fact:
    package_install_list: "{{ freckles_metadata | create_package_list_filter }}"

- name: auto-detect package managers
  set_fact:
    required_package_managers: "{{ package_install_list | pkg_mgr_filter }}"

- name: install required package managers
  include_role:
    name: makkus.install-pkg-mgrs
  vars:
    pkg_mgrs: "{{ required_package_managers }}"
    default_pkg_mgr: "{{ pkg_mgr | default(omit) }}"

- name: install freckle packages that need ansible roles
  include: "role-install-{{ role_package['vars']['name'] }}.yml"
  when: "role_package['vars'].get('pkg_mgr', 'auto') == 'ansible_role'"
  with_items:
    - "{{ package_install_list }}"
  loop_control:
    loop_var: role_package

- name: install freckle packages
  install:
    packages: "{{ item }}"
    pkg_mgr: "{{ pkg_mgr }}"
  ignore_errors: "{{ ignore_errors | default(true) }}"
  when: "item['vars'].get('pkg_mgr', 'auto') != 'ansible_role'"
  with_items:
    - "{{ package_install_list }}"

- name: "starting profile execution"
  include: "{{ profile_loop_item.key }}.yml"
  vars:
    freckle_profile_folders: "{{ profile_loop_item.value }}"
  when: "profile_loop_item.key != '__freckles_default__'"
  with_dict: "{{ freckles_metadata | flatten_profiles_filter }}"
  loop_control:
    loop_var: profile_loop_item


