---
# tasks file for dotfiles
- name: "[initialize box with basic requirements]"
  include_role:
    name: makkus.box-basics

- name: checking out freckle(s)
  git:
    dest: "{{ item.dest }}"
    repo: "{{ item.repo }}"
  when: "item.repo is defined and item.repo"
  with_items:
    - "{{ freckles | git_repo_filter }}"

- name: "[finding freckles folders]"
  freckles_facts:
    freckles_repos: "{{ freckles }}"

# can only do that on the controller, because dependency requirements
- name: "[processing freckles folders]"
  set_fact:
    freckles_metadata: "{{ freckles_folders_raw | read_profile_vars_filter }}"

- name: "[including profile]"
  include: "profile.yml"
  vars:
    freckles_profile_name: "{{ profile_loop_item.key }}"
    freckles_profile_folders: "{{ profile_loop_item.value }}"
  with_dict: "{{ freckles_metadata | flatten_profiles_filter }}"
  loop_control:
    loop_var: profile_loop_item


# Ansible 2.3 doesn't support vars in include_role
# - name: "starting profile execution"
#   include_role:
#     #name: "{{ profile_loop_item.key }}"
#     name: "{{ role_name }}"
#   vars:
#     freckle_profile_folders: "{{ profile_loop_item.value }}"
#   static: no
#   with_dict: "{{ freckles_metadata | flatten_profiles_filter }}"
#   loop_control:
#     loop_var: profile_loop_item
