---
# tasks file for python-dev
- name: "[checking for Mac OS X dependencies]"
  include: python-dev-darwin.yml
  static: no
  when: "ansible_os_family == 'Darwin' and (pkg_mgr is not defined or pkg_mgr != 'conda')"

- name: installing python dependencies
  include_role:
    name: makkus.install-packages
  vars:
    profile_name: python-dev
    package_install_list:
      - vars:
          name: build-essential
          pkgs:
            debian:
              - build-essential
            other: omit
      - vars:
          name: build-dependencies
          pkgs:
            debian:
              - python-dev
              - python-virtualenv
              - python-pip
            other: omit

- name: "[starting python project setup]"
  include: python-dev-item.yml
  static: no
  vars:
    project_path: "{{ python_project_item.key }}"
    project_details: "{{ python_project_item.value }}"
  with_dict: "{{ freckles_profile_folders }}"
  loop_control:
    loop_var: python_project_item
