- name: setting project name
  set_fact:
    project_name: "{{ project_path | project_name_filter }}"

- name: creating conda environment
  conda:
    name: "python={{ python_version | default(default_python_version) }}"
    conda_environment: "{{ project_name }}-dev"
  when: "pkg_mgr is defined and pkg_mgr == 'conda'"

- name: installing python project dependencies
  include_role:
    name: makkus.install-packages
  vars:
    profile_name: "project dependency"
    conda_environment: "{{ project_name }}-dev"
    package_install_list: "{{ project_details.get('vars', []) | create_package_list_from_var_filter('packages') }}"

- name: installing python dev requirements (into conda environment)
  install:
    pkg_mgr: pip
    executable: "~/.local/inaugurate/conda/envs/{{ project_name }}-dev/bin/pip"
    packages:
      - "{{ project_path }}/requirements_dev.txt"
  when: "pkg_mgr is defined and pkg_mgr == 'conda'"

- name: installing python dev requirements (into virtualenv)
  install:
    pkg_mgr: pip
    #executable: "~/.local/opt/conda/envs/{{ project_name}}-dev/bin/pip"
    virtualenv: "~/.local/virtualenvs/{{ project_name }}-dev"
    packages:
      - "{{ project_path }}/requirements_dev.txt"
  when: "pkg_mgr is not defined or pkg_mgr == 'auto'"

- name: "running 'python setup.py develop' in conda environment"
  command: "~/.local/inaugurate/conda/envs/{{ project_name }}-dev/bin/python setup.py develop"
  args:
    chdir: "{{ project_path }}"
  when: "pkg_mgr is defined and pkg_mgr == 'conda'"

- name: "running 'python setup.py develop' in project virtualenv"
  command: "~/.local/virtualenvs/{{ project_name }}-dev/bin/python setup.py develop"
  args:
    chdir: "{{ project_path }}"
  when: "pkg_mgr is not defined or pkg_mgr == 'auto'"
